config/routes.rb
Myapp::Application.routes.draw do

  resources :about_mes
  # You can have the root of your site routed with "root"
  # root to: 'dashboards#dashboard_1'

  root to: 'members#sign_in'

  # All routes
  get 'welcome/welcome'
  post 'members/login_with_password'
  get 'application/logout'
  resources :banner_introduces

  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/autocomplete"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/banner_introduce.rb
class BannerIntroduce < ApplicationRecord
  validates :title, :little_title, :description, presence: true

end

app/controllers/banner_introduces_controller.rb
class BannerIntroducesController < ApplicationController
  before_action :find_banner_introduce, only: [:show, :edit, :update, :destroy]


  def index
    @introduces = BannerIntroduce.all
  end

  def new
    @introduce = BannerIntroduce.new
  end

  def show

  end

  def edit
    @introduce_detail = BannerIntroduce.find(params[:id])
  end

  def create
    Rails.logger.info "=================#{introduce_params.inspect}"
      @introduce = BannerIntroduce.new(introduce_params)
    if @introduce.valid?
      # @introduce = BannerIntroduce.new(title: params[:title], little_title: params[:little_title], description: params[:description])
      @introduce.save!
      redirect_to banner_introduces_path
    end

  end

  def update
    @introduce = BannerIntroduce.find(params[:id])
    if @introduce.valid? @introduce.update(introduce_params)
      redirect_to banner_introduces_path

    end

  end

  def destroy
    @introduce.destroy!
    redirect_to banner_introduces_path
  end


  private

  def find_banner_introduce
    @introduce = BannerIntroduce.find(params[:id])
  end

  def introduce_params
    params.require(:introduce).permit(:title, :little_title, :description)
  end

end

app/helpers/banner_introduce_helper.rb
module BannerIntroduceHelper
end

app/views/banner_introduces/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>编辑Banner图个人介绍</h5>
          <!--          <div class="ibox-tools">-->
          <!--            <a class="collapse-link">-->
          <!--              <i class="fa fa-chevron-up"></i>-->
          <!--            </a>-->
          <!--            <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--              <i class="fa fa-wrench"></i>-->
          <!--            </a>-->
          <!--            <ul class="dropdown-menu dropdown-user">-->
          <!--              <li><a href="#">Config option 1</a>-->
          <!--              </li>-->
          <!--              <li><a href="#">Config option 2</a>-->
          <!--              </li>-->
          <!--            </ul>-->
          <!--            <a class="close-link">-->
          <!--              <i class="fa fa-times"></i>-->
          <!--            </a>-->
          <!--          </div>-->
        </div>
        <div class="ibox-content">

            <%= form_with model: @introduce , html: {class: "form-horizontal"} do |f| %>
              <div class="form-group"><label class="col-sm-2 control-label">大标题</label>

                <div class="col-sm-10">
                  <input type="text" class="form-control" name="introduce[title]" value="<%= @introduce_detail.try(:title) %>" placeholder="请输入大标题">
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">小标题</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="introduce[little_title]" value="<%= @introduce_detail.try(:little_title) %>" placeholder="请输入小标题">
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">个人描述</label>
                <div class="col-sm-10">
                  <textarea rows="5" class="form-control" name="introduce[description]" placeholder="请输入个人描述"><%= @introduce_detail.try(:description) %></textarea>
                </div>
              </div>
              <div class="hr-line-dashed"></div>


              <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                  <%= link_to raw("<i class='fa fa-arrow-left'></i> 取消"), banner_introduces_path, class: "btn btn-default btn-sm" %>
                  <%= button_tag(:class => "btn btn-primary btn-sm") do %>
                    <i class="fa fa-check"></i> 提交
                  <% end %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/banner_introduces/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Banner部分个人介绍 </h5>
          <div class="ibox-tools">
            <%= link_to raw("<i class='fa fa-plus'></i>  新增"), new_banner_introduce_path,  class: "btn btn-primary btn-sm"%>
          </div>
        </div>
        <div class="ibox-content">

          <table class="table table-hover">
            <thead>
            <tr>
              <th>#ID</th>
              <th>大标题</th>
              <th>小标题</th>
              <th>个人描述</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% @introduces.each do |introduce| %>
            <tr>
              <td><%= introduce.id %></td>
              <td class="text-navy"><%= introduce.title %></td>
              <td class="text-warning"><%= introduce.little_title %></td>
              <td class="text-success"><%= introduce.description %></td>
              <td>
                <%= link_to raw("<i class='fa fa-info-circle'></i> 查看"), banner_introduce_path(introduce),  class: "btn btn-default btn-xs"%>
                <%= link_to raw("<i class='fa fa-edit'></i> 编辑"), edit_banner_introduce_path(introduce),  class: "btn btn-success btn-xs"%>
                <%= link_to raw("<i class='fa fa-trash-o'></i> 删除"), banner_introduce_path(introduce),  method: :delete, data: { confirm: "确定删除吗?" }, class: "btn btn-danger btn-xs" %>
              </td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/banner_introduces/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>新增Banner图个人介绍</h5>
          <!--          <div class="ibox-tools">-->
          <!--            <a class="collapse-link">-->
          <!--              <i class="fa fa-chevron-up"></i>-->
          <!--            </a>-->
          <!--            <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--              <i class="fa fa-wrench"></i>-->
          <!--            </a>-->
          <!--            <ul class="dropdown-menu dropdown-user">-->
          <!--              <li><a href="#">Config option 1</a>-->
          <!--              </li>-->
          <!--              <li><a href="#">Config option 2</a>-->
          <!--              </li>-->
          <!--            </ul>-->
          <!--            <a class="close-link">-->
          <!--              <i class="fa fa-times"></i>-->
          <!--            </a>-->
          <!--          </div>-->
        </div>
        <div class="ibox-content">


          <%= form_for :introduce, html: {class: "form-horizontal"}, url: banner_introduces_path do |f| %>
            <div class="form-group"><label class="col-sm-2 control-label">大标题</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="introduce[title]" placeholder="请输入大标题">
              </div>
            </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group"><label class="col-sm-2 control-label">小标题</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="introduce[little_title]" placeholder="请输入小标题">
              </div>
            </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group"><label class="col-sm-2 control-label">个人描述</label>
              <div class="col-sm-10">
                <textarea type="text" rows="5" class="form-control" name="introduce[description]" placeholder="请输入个人描述"></textarea>
              </div>
            </div>
            <div class="hr-line-dashed"></div>


            <div class="form-group">
              <div class="col-sm-4 col-sm-offset-2">
                <%= link_to raw("<i class='fa fa-arrow-left'></i> 返回"), banner_introduces_path, class: "btn btn-default btn-sm" %>
                <%= button_tag(:class => "btn btn-primary btn-sm") do %>
                  <i class="fa fa-check"></i> 提交
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/banner_introduces/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>查看Banner图个人介绍</h5>
          <!--          <div class="ibox-tools">-->
          <!--            <a class="collapse-link">-->
          <!--              <i class="fa fa-chevron-up"></i>-->
          <!--            </a>-->
          <!--            <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--              <i class="fa fa-wrench"></i>-->
          <!--            </a>-->
          <!--            <ul class="dropdown-menu dropdown-user">-->
          <!--              <li><a href="#">Config option 1</a>-->
          <!--              </li>-->
          <!--              <li><a href="#">Config option 2</a>-->
          <!--              </li>-->
          <!--            </ul>-->
          <!--            <a class="close-link">-->
          <!--              <i class="fa fa-times"></i>-->
          <!--            </a>-->
          <!--          </div>-->
        </div>
        <div class="ibox-content">
          <form method="get" class="form-horizontal">

            <div class="form-group"><label class="col-lg-2 control-label">大标题</label>

              <div class="col-lg-10"><p class="form-control-static"><%= @introduce.title %></p></div>
            </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group"><label class="col-lg-2 control-label">小标题</label>

              <div class="col-lg-10"><p class="form-control-static"><%= @introduce.little_title %></p></div>
            </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group"><label class="col-lg-2 control-label">个人描述</label>

              <div class="col-lg-10"><p class="form-control-static"><%= @introduce.description %></p></div>
            </div>
            <div class="hr-line-dashed"></div>


            <div class="form-group">
              <div class="col-sm-4 col-sm-offset-0">
                <%= link_to raw("<i class='fa fa-arrow-left'></i> 返回"), banner_introduces_path,  class: "btn btn-default btn-sm"%>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>