config/routes.rb
Myapp::Application.routes.draw do

  resources :about_mes
  # You can have the root of your site routed with "root"
  # root to: 'dashboards#dashboard_1'

  root to: 'members#sign_in'

  # All routes
  get 'welcome/welcome'
  post 'members/login_with_password'
  get 'application/logout'
  resources :banner_introduces

  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/autocomplete"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/datamaps"
  get "miscellaneous/social_buttons"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/pdf_viewer"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/helper_classes"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/about_me.rb
class AboutMe < ApplicationRecord
    validates :birthday, :graduated_from, :website, :hobby, :address, :title, :description, presence: true
end

app/controllers/about_mes_controller.rb
class AboutMesController < ApplicationController
  before_action :set_about_me, only: %i[ show edit update destroy ]

  # GET /about_mes or /about_mes.json
  def index
    @about_mes = AboutMe.all
  end

  # GET /about_mes/1 or /about_mes/1.json
  def show
  end

  # GET /about_mes/new
  def new
    @about_me = AboutMe.new
  end

  # GET /about_mes/1/edit
  def edit
  end

  # POST /about_mes or /about_mes.json
  def create
    @about_me = AboutMe.new(about_me_params)

    if @about_me.valid?
      Rails.logger.info "====================="
      @about_me.save!
      redirect_to about_mes_path
    end
  end

  # PATCH/PUT /about_mes/1 or /about_mes/1.json
  def update
    if @about_me.valid?
      @about_me.update(about_me_params)
      redirect_to about_mes_path
    end
  end

  # DELETE /about_mes/1 or /about_mes/1.json
  def destroy
    @about_me.destroy
    redirect_to about_mes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about_me
      @about_me = AboutMe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def about_me_params
      params.require(:about_me).permit(:birthday, :graduated_from, :website, :hobby, :address, :title, :description)
    end
end

app/helpers/about_mes_helper.rb
module AboutMesHelper
end

app/views/about_mes/_form.html.erb
<%= form_with(model: about_me, local: true, html: {class: "form-horizontal"}) do |form| %>
 

  <div class="form-group">
    <%= form.label :生日, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :birthday, class: "form-control", placeholder: "请输入生日" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= form.label :毕业于, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :graduated_from, class: "form-control", placeholder: "请输入毕业院校" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= form.label :网站, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :website, class: "form-control", placeholder: "请输入个人网站地址" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= form.label :爱好, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :hobby, class: "form-control", placeholder: "请输入爱好" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= form.label :地址, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :address, class: "form-control", placeholder: "请输入地址" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= form.label :标题, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control", placeholder: "请输入标题" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= form.label :描述, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_area :description, class: "form-control", rows: "5", placeholder: "请输入个人描述" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
      <div class="col-sm-4 col-sm-offset-2">
        <%= link_to raw("<i class='fa fa-arrow-left'></i> 返回"), about_mes_path, class: "btn btn-default btn-sm" %>
        <%= button_tag(:class => "btn btn-primary btn-sm") do %>
          <i class="fa fa-check"></i> 提交
        <% end %>
      </div>
  </div>
<% end %>

app/views/about_mes/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>编辑关于我</h5>
          <!--          <div class="ibox-tools">-->
          <!--            <a class="collapse-link">-->
          <!--              <i class="fa fa-chevron-up"></i>-->
          <!--            </a>-->
          <!--            <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--              <i class="fa fa-wrench"></i>-->
          <!--            </a>-->
          <!--            <ul class="dropdown-menu dropdown-user">-->
          <!--              <li><a href="#">Config option 1</a>-->
          <!--              </li>-->
          <!--              <li><a href="#">Config option 2</a>-->
          <!--              </li>-->
          <!--            </ul>-->
          <!--            <a class="close-link">-->
          <!--              <i class="fa fa-times"></i>-->
          <!--            </a>-->
          <!--          </div>-->
        </div>
        <div class="ibox-content">

           <%= render 'form', about_me: @about_me %>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/about_mes/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>关于我</h5>
          <div class="ibox-tools">
            <%= link_to raw("<i class='fa fa-plus'></i>  新增"), new_about_me_path,  class: "btn btn-primary btn-sm"%>
          </div>
        </div>
        <div class="ibox-content">

          <table class="table table-hover">
            <thead>
            <tr>
              <th>#ID</th>
              <th>生日</th>
              <th>毕业于</th>
              <th>网站</th>
              <th>爱好</th>
              <th>地址</th>
              <th>标题</th>
              <th>描述</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% @about_mes.each do |about_me| %>
            <tr>
              <td class="text-success"><%= about_me.id %></td>
              <td class="text-success"><%= about_me.birthday %></td>
              <td class="text-success"><%= about_me.graduated_from %></td>
              <td class="text-success"><%= about_me.website %></td>
              <td class="text-success"><%= about_me.hobby %></td>
              <td class="text-success"><%= about_me.address %></td>
              <td class="text-success"><%= about_me.title %></td>
              <td class="text-success"><%= about_me.description %></td>
              <td>
                <%= link_to raw("<i class='fa fa-info-circle'></i> 查看"), about_me_path(about_me),  class: "btn btn-default btn-xs"%>
                <%= link_to raw("<i class='fa fa-edit'></i> 编辑"), edit_about_me_path(about_me),  class: "btn btn-success btn-xs"%>
                <%= link_to raw("<i class='fa fa-trash-o'></i> 删除"), about_me_path(about_me),  method: :delete, data: { confirm: "确定删除吗?" }, class: "btn btn-danger btn-xs" %>
              </td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/about_mes/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>新增关于我</h5>
          <!--          <div class="ibox-tools">-->
          <!--            <a class="collapse-link">-->
          <!--              <i class="fa fa-chevron-up"></i>-->
          <!--            </a>-->
          <!--            <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--              <i class="fa fa-wrench"></i>-->
          <!--            </a>-->
          <!--            <ul class="dropdown-menu dropdown-user">-->
          <!--              <li><a href="#">Config option 1</a>-->
          <!--              </li>-->
          <!--              <li><a href="#">Config option 2</a>-->
          <!--              </li>-->
          <!--            </ul>-->
          <!--            <a class="close-link">-->
          <!--              <i class="fa fa-times"></i>-->
          <!--            </a>-->
          <!--          </div>-->
        </div>
        <div class="ibox-content">

           <%= render 'form', about_me: @about_me %>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/about_mes/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>查看Banner图个人介绍</h5>
          <!--          <div class="ibox-tools">-->
          <!--            <a class="collapse-link">-->
          <!--              <i class="fa fa-chevron-up"></i>-->
          <!--            </a>-->
          <!--            <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--              <i class="fa fa-wrench"></i>-->
          <!--            </a>-->
          <!--            <ul class="dropdown-menu dropdown-user">-->
          <!--              <li><a href="#">Config option 1</a>-->
          <!--              </li>-->
          <!--              <li><a href="#">Config option 2</a>-->
          <!--              </li>-->
          <!--            </ul>-->
          <!--            <a class="close-link">-->
          <!--              <i class="fa fa-times"></i>-->
          <!--            </a>-->
          <!--          </div>-->
        </div>
        <div class="ibox-content">
          <form method="get" class="form-horizontal">

            <div class="form-group">
              <label class="col-lg-2 control-label">生日:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.birthday %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <label class="col-lg-2 control-label">毕业于:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.graduated_from %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <label class="col-lg-2 control-label">网站:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.website %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <label class="col-lg-2 control-label">爱好:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.hobby %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <label class="col-lg-2 control-label">地址:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.address %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <label class="col-lg-2 control-label">标题:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.title %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <label class="col-lg-2 control-label">描述:</label>
                <div class="col-lg-10"><p class="form-control-static"><%= @about_me.description %></p></div>
              </div>
            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <div class="col-sm-4 col-sm-offset-0">
                <%= link_to raw("<i class='fa fa-arrow-left'></i> 返回"), about_mes_path,  class: "btn btn-default btn-sm"%>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>